### PR TITLE
Added support for cordova InAppBrowser

### PR DESCRIPTION
**Pull request by crtek**
If you like to use this library with cordova.js you need to fetch the code and hash from inappbrowsers loadstart event.
I'm also passing the config from satellizer.Oauth1 and satellizer.Oauth2 to satellizer.popup.open method,
so that i can check redirectUri

### CODE REVIEW

**Comment by sahat** [comment]
Hi @crtek I have no way to test this since I do not have experience with Ionic or Cordova, or have those installed on my machine. Before I merge this could you clean up the code starting with consistent spacing and indentation. Also, you can skip all that ceremony with === or !== to `null` or `undefined` in if statements. 

Lastly, could you do a rebase of your commits?

Thanks!

**Comment by crtek** [comment]
ok,
i'll clean my code.
I'm a noob with github so bear with me please

Thanks!

**Comment by crtek** [comment]
hi @sahat i did a rebase,
hope it is ok now

**Comment by krystalcode** [comment]
Hi @crtek , I have also worked on making satellizer available for mobile (Ionic/Cordova) and I have created a pull request https://github.com/sahat/satellizer/pull/294.

Have a look and let's talk what's the best way to do this.

**Comment by rochacon** [comment]
Worked fine on a Android emulator with an Ionic/Cordova app. :+1:

**Comment by crtek** [comment]
Hi @krystalcode, I have seen your PR. Seems cleaner than mine. 
Avoiding the polling method seems better.
I made a few changes so that it works with twitter too, but i can't fork your repository and
can not pr. Can you tell me how can i send you my changes.

**Comment by krystalcode** [comment]
Hi @crtek , I have added you as a collaborator to my fork krystalcode/satellizer. I suggest that we do the following:

1. You can commit your code directly to my fork into a branch.
2. We review, discuss, improve together.
3. When ready, we make a pull request and @sahat can merge it to sahat/satellizer.

Let me know if that works for you.

**Comment by crtek** [comment]
Hi @krystalcode,
your suggestion souns good to me.
PS: sorry for the late response, I was on vacation

**Comment by raibutera** [comment]
@krystalcode @crtek hi guys, any news on this?

**Comment by crtek** [comment]
@raibutera  hi this functionality was merged with pull request #294

**Comment by krystalcode** [comment]
It might be best to close this pull request as mobile support (for OAuth2) has already been merged.

**Pull request closed without merging**
