### PR TITLE
Nicer bool cast

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by sahat** [comment]
This actually needed a single ! because of the way the comparison is constructed.

**Comment by graingert** [comment]
Oh that's weird probably best to swap the operator then

**Comment by sahat** [comment]
It makes sense if you think about in terms of expiration date relative to current date, but not in the context of "Are you authenticated?" Now that I think about it, it's a lot cleaner this way:

```js
return Math.round(new Date().getTime() / 1000) < exp;
```

= As long as current time is less than the expiration time, yes, I am authenticated.

**Comment by graingert** [comment]
And you don't need the !!

**Pull request merged**
