### PR TITLE
Allow token exchange parameters to be specified in config

### PR DESCRIPTION
**Pull request by rharriso**

### CODE REVIEW

**Comment by rharriso** [comment]
@sahat, any opinion on this pull request? Without it is insn't possible to make compatible with some OAuth providers, e.g. Rails' doorkeeper.

**Comment by sahat** [comment]
Hi @rharriso,

Is `responseParams` not sufficient for you? What does `exchangeParams` provide that cannot be already set via `responseParams`?

I am not very familiar with Doorkeeper so some context would be helpful and why this change is necessary.

**Comment by rharriso** [comment]
Currently there is no way to adjust the set of parameter content or names when making the exchange request. Here is how I'm using exchange parameters in my app.

`

  app.config(["$authProvider", function($authProvider){
    $authProvider.oauth2({
      name: 'auth_app_name',
      responseType: 'code',
      clientId: "<%=ENV["AUTH_APP_CLIENT_ID"]%>",
      redirectUri: "<%=ENV['AUTH_APP_CALLBACK']%>",
      authorizationEndpoint: "<%=ENV["RUCKSACK_HOST"]%>/oauth/authorize", 
      url: "<%=ENV["AUTH_APP_HOST"]%>/oauth/token",
      exchangeParams: {
        client_secret: "<%=ENV["AUTH_APP_SECRET"]%>",
        client_id: "<%=ENV["AUTH_APP_CLIENT_ID"]%>",
        redirect_uri: "<%=ENV['AUTH_APP_CALLBACK']%>",
        grant_type: "authorization_code"
      }
    }); 
  }]);

`

**Comment by sahat** [comment]
@rharriso I will consider merging this PR if you could combine the logic of responseParams and exchangeParams into a single config options. It could still be called responseParams.

It's just I can't keep adding more and more options to satisfy every user request without bloating the API and making the project more complex.

**Comment by rharriso** [comment]
@sahat,

My company has decided to go with another flow (avoiding popups). So I'm not going to continue working on these changes. Best of luck with your project!

**Pull request closed without merging**
