### PR TITLE
Update AuthController.php

### PR DESCRIPTION
**Pull request by jmrhib**
Send User object  instead of array to createToken method.

### CODE REVIEW

**Comment by DonLiborio** [comment]
jmrhib, I'm writing here because I don't know any other way to contact you. Somewhere you mentioned that you implemented satellizer with Slim. I'd be curious to see your solution, as I'm already using Slim for a REST interface. Would you care to share the code? Many thanks!

**Comment by jmrhib** [comment]
Hi. There are a few things which needs to be cleaned up first. I could share it with you, and/or post it to github within a week or so.

-johannes.
________________________________
Fra: DonLiborio [notifications@github.com]
Sendt: 16. august 2015 21:07
Til: sahat/satellizer
Kopi: Johannes Mario Ringheim
Emne: Re: [satellizer] Update AuthController.php (#196)


jmrhib, I'm writing here because I don't know any other way to contact you. Somewhere you mentioned that you implemented satellizer with Slim. I'd be curious to see your solution, as I'm already using Slim for a REST interface. Would you care to share the code? Many thanks!

**Comment by DonLiborio** [comment]
That'd be awesome, many thanks, Johannes!

**Comment by jmrhib** [comment]
Have posted it here:
https://github.com/jmrhib/satellizer-slim-backend

**Comment by DonLiborio** [comment]
That's great, many thanks!!

**Pull request merged**
