### PR TITLE
Added native support for twitch.tv API

### PR DESCRIPTION
**Pull request by manumiranda**
I can also make the example but I need a clientId for twitch.tv

### CODE REVIEW

**Comment by sahat** [comment]
Thank you I'll add the example.

**Comment by sahat** [comment]
@manumiranda How do you view existing Twitch OAuth 2.0 apps after they are created?

You would think it would be http://www.twitch.tv/kraken/oauth2/clients but that returns an error *Requests must be made over SSL* and using **https** doesn't work either.

I mean I have seen some terrible developer-focused UX for some APIs, but this is just beyond abysmal. It shouldn't be that hard to be able to view my existing apps. @mpoon @Hebo I hope you could chime in here.

**Comment by sahat** [comment]
Twitch API example (Node.js only so far) is now available on `master` branch.

screenshot 2015-08-21 22 54 37

screenshot 2015-08-21 22 59 53

**Comment by manumiranda** [comment]
@sahat I am new to this OAuth thing, to be honest I didn't even know that there should be some path to get the installed apps. I'll try to investigate it but hopefully @mpoon or @Hebo will shed some light on this. 

Thanks for the merge =)

**Pull request merged**
