### PR TITLE
Support for Mobile

### PR DESCRIPTION
**Pull request by krystalcode**
Added support for mobile authentication. Tested using the Ionic framework and Facebook, Google, already used in production. It includes an example under the examples folder examples/ionic.

Noticeable changes:

1. Added a configuration option "platform" that defaults to "browser". If "mobile" is provided, it listens to the loadstart event rather than use the polling method.

Things remain to be done:

1. Only OAuth2 supported, no work/testing was done for OAuth1.
2. Update the README.md with instructions for mobile.

If you are interested in integrating this, I can provide steps to test.

[Review on Reviewable](https://reviewable.io/reviews/sahat/satellizer/294)

### CODE REVIEW

**Comment by jamhall** [comment]
@krystalcode - Thank you for these changes. I'll be using your fork until the changes are merged.

**Comment by sahat** [comment]
Thanks for the PR. I will add more OAuth example to Ionic over the weekend.

**Comment by bigali** [comment]
I integrated the social authentication to my Ionic app and it works perfectly ,but when i added crosswalk it do not work , how can i fix this , thanks

**Comment by krystalcode** [comment]
Hi @bigali , I haven't gotten into crosswalk yet so I haven't tested it. Any debugging information would be helpful, at which step of the process does it fail?
If you provide steps with how to test with crosswalk (incl. what do I need to do to enable crosswalk), or a link to a guide, I will test it when I get some time.

**Comment by bigali** [comment]
hi @krystalcode ,to add crosswalk use ionic cli, "ionic browser add crosswalk",  you can use chrome dev tools (chrome://inspect)  to debug the app ,  https://www.youtube.com/watch?v=57hsxvCrBdE   a video explaning debug steps.
inappbrowser opens correctly but when it return to my app , isauthentifcated variable is still false , and it do not redirect me to the correct route.
ps: crosswalk increase performances dramaticly on android,and i really need performance my project

**Comment by sahat** [comment]
@krystalcode What did you use for Facebook's Site URL?           
screenshot 2015-06-08 14 18 00

**Comment by sahat** [comment]
Nevermind, you have to set it to `http://localhost/`.

**Pull request merged**
