### PR TITLE
Remove withCredential from oauth2.exchangeForToken

### PR DESCRIPTION
**Pull request by amitaibu**
#263

### CODE REVIEW

**Comment by sahat** [comment]
@amitaibu Have you searched GitHub issues to see that it was added in https://github.com/sahat/satellizer/pull/211?

**Comment by amitaibu** [comment]
@sahat sorry I didn't see the issue - I used git blame and it have a commit that was hard to understand the source of it. Anyway, I'll improve the PR to make withCredentials optional - as I did in my initial PR

**Comment by amitaibu** [comment]
@sahat updated the PR

**Comment by sahat** [comment]
Thank you for the PR.

**Pull request merged**
