### PR TITLE
Remove es6 features

### PR DESCRIPTION
**Pull request by mattlewis92**
This will save users having to provide polyfills for Object.assign and Promise's (using $q also gives the benefit of being able to hook into angulars digest cycle)

### CODE REVIEW

**Comment by sahat** [comment]
@mattlewis92 Does TypeScript compiler not provide polyfills for something as trivial as Object.assign and Promise?

Another related question, is `angular.extend` and `$q` available in Angular 2?

**Comment by mattlewis92** [comment]
Typescript doesn't provide any code transformations like babel does with it's transform-runtime plugin (you can confirm this in the transpiled source) https://github.com/sahat/satellizer/blob/master/dist/satellizer.js)

In angular2 you would just use the native Object.assign and Promise (and angular2 has the benefit of being written in ES6 hence it is assumed that you are already including the ES6 shim, unlike ng1).

I think maybe something like a SatellizerShims service might work, so you have:
```
// ng1
SatellizerShims.Promise = $q;
SatellizerShims.extend = angular.extend;
// ng2
SatellizerShims.Promise = Promise;
SatellizerShims.extend = Object.assign;
```

and then the rest of the code just uses `SatellizerShims.Promise` instead of `window.Promise`. A good example of this is the ui-router which shares the same core code and then has small wrappers that sit over the top for ng1 and ng2: https://github.com/angular-ui/ui-router/blob/master/src/common/coreservices.ts

**Comment by sahat** [comment]
I don't know when Angular 2 support will be ready, that's why I am going to merge this PR for now. Thanks!

**Comment by mattlewis92** [comment]
Great, thanks! I gave some more thought on how better to share the code between ng1 and ng2, and I have a pretty decent idea of how to do it, I will put together a PR over the next couple of weeks with a prototype 😄 

In the meantime could you cut a new release so I can upgrade to the latest version? Thanks!

**Comment by sahat** [comment]
I will do that tonight. 

Here is my initial attempt at HTTP wrapper and OAuth1 service code sharing. https://github.com/sahat/satellizer/tree/ng2. It is based on this idea: https://github.com/sahat/satellizer/issues/320#issuecomment-202805851

**Comment by mattlewis92** [comment]
Ah I hadn't thought of making use of typescripts interfaces to ensure the API contract, that makes  a lot of sense, I think injecting the values into each classes constructor is cleaner than using a shared object which is what ui-router does. It might even be worth splitting out the shimming logic into a separate module.

**Pull request merged**
