### PR TITLE
Toggle session and local storage

### LINKED ISSUE #385: Need to be able to switch storage for Remember Me
When user check remember me I need to save it into local storage
When user uncheck remember me save to session storage
How can we do this?
It is not able to let me switch storage. We need to support this

### PR DESCRIPTION
**Pull request by TheOneTheOnlyDavidBrown**
closes #385

### CODE REVIEW

**Comment by sahat** [comment]
@TheOneTheOnlyDavidBrown just so I understand correctly this works in conjunction with `$authProvider.storage` that I introduced recently?

**Comment by TheOneTheOnlyDavidBrown** [comment]
Yes. It accesses the same config setting as $authProvider.storage but allows the developer to set it outside of the module's config. This way the developer can change the storage type based on whether or not a 'remember me' checkbox is checked

**Comment by tianxu0836** [comment]
Just to make sure, if I call $auth.setStorage to session storage when remember me is unchecked, after login it will get token from session storage instead of default local storage, right?

**Comment by akkie** [comment]
@TheOneTheOnlyDavidBrown @sahat I may be wrong, but are you both sure that this works as expected. In my opinion the storage factory gets initialized once based on the value defined with `$authProvider.storage`. After that it isn't possible to change the storage based on the config value. Please correct me if I'm wrong.

**Comment by tianxu0836** [comment]
From my point of view it is not possible to change the storage based on the
config value..... This really gives me lots of trouble.

**Pull request merged**
