### PR TITLE
Missing return statement & ordering concern

### PR DESCRIPTION
**Pull request by justinzelinsky**
- Missing return statement
- The state must be stored before the query string generator builder can run

### CODE REVIEW

**Comment by sahat** [comment]
Return statement is not necessary when using arrow functions. For example:

```js
var a2 = a.map(function(s){ return s.length });
// is equal to:
var a3 = a.map( s => s.length );
```

**Comment by justinzelinsky** [comment]
From [Arrow functions (MDN)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
> Basic Syntax
> 
> (param1, param2, …, paramN) => { statements }
> (param1, param2, …, paramN) => expression
>          // equivalent to:  => { return expression; }

Your example above is the second syntax. The code in the application is the first. So, we either need to just remove the {}'s

**Comment by sahat** [comment]
Yeah sorry I just realized my mistake. You are right.

**Comment by justinzelinsky** [comment]
Let me fix that.

**Comment by sahat** [comment]
👍 Thanks, that's better.

**Pull request merged**
