### PR TITLE
Make $auth.login more flexible

### PR DESCRIPTION
**Pull request by gustavolira**
Added another parameter to $auth.login to make possible change the loginUrl for specific ponints at application

### CODE REVIEW

**Comment by sahat** [comment]
I will add this feature in the next release, but it will implemented slightly differntly. I am going to keep only 2 params inside `login()` - user object with email/password and options. You will be able to customize the login url via `options.url` or something like that.

**Comment by RobertHerhold** [comment]
@sahat 

Please consider allowing adding other properties like headers, as I suggested in #440

**Comment by sahat** [comment]
@RobertHerhold If i am going to add request options parameter, I will probably remove `redirect`, as I don't want to make method signature even more complicated than it already is.

Ditching all this `redirect` may be a good idea, and let you do your own redirects, e.g.:

```js
$auth.login(user)
  .then(function() {
  // redirect yourself on successful login
  });

**Comment by sahat** [comment]
Resolved in [0.12](https://github.com/sahat/satellizer/releases/tag/0.12.0) release.

**Pull request closed without merging**
