### PR TITLE
fixed error on firefox: [ Error] [:inprog]  already in progress

### PR DESCRIPTION
**Pull request by viniciusdacal**
@sahat
this closes issue #569

### CODE REVIEW

**Comment by viniciusdacal** [comment]
do not merge this yet, all unit tests are ok, but there is still an error.

**Comment by sahat** [comment]
Thanks. I fixed the problem you were having where popup is never closed. Please check `master` branch and let me know if that fixes "already in progress" error.

**Comment by sahat** [comment]
I had to manually merge these changes due to merge conflicts, here is the commit. 76ba026870c0734ba54fa55bb23402f7d9c70e60

**Comment by sahat** [comment]
By the way is this really necessary?
```js
defer.resolve(Oauth2.exchangeForToken(oauthData, userData));
```

`Oauth2.exchangeForToken(oauthData, userData)` already returns a promise, so couldn't it just do `return Oauth2.exchangeForToken(oauthData, userData)` as before?

**Comment by viniciusdacal** [comment]
@sahat 
acctually, I think it is, because this code is inside a $timeout, so, to work the promise we need to use defer.

**Pull request closed without merging**
