### PR TITLE
use anonymous interceptor

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by sahat** [comment]
Why?

**Comment by graingert** [comment]
@sahat why polute the namespace?

**Comment by sahat** [comment]
Ok, I just couldn't understand why change it without any sort of description. The satellizer.js file is going to be replaced by new `typescript` branch soon.
https://github.com/sahat/satellizer/blob/typescript/src/httpProviderConfig.ts
https://github.com/sahat/satellizer/blob/typescript/src/interceptor.ts

In this case would I need to replace `'SatellizerInteceptor'` string with an actual `Intereceptor.js` class import reference?
```js
constructor(private $httpProvider: angular.IHttpProvider) {
    $httpProvider.interceptors.push('SatellizerInterceptor');
}
```

**Comment by graingert** [comment]
@sahat yes.

**Pull request closed without merging**
