### PR TITLE
Add possibility to choose method for exchangeForToken call

### PR DESCRIPTION
**Pull request by timsly**

### CODE REVIEW

**Comment by amitaibu** [comment]
Why not use ``POST``?

**Comment by timsly** [comment]
In my project i need `POST` for oauth1 call as well. So i thought that it would be nice if we can customize method

**Comment by sahat** [comment]
Sorry for being so late to the party, but I have decided not to merge this PR. 

If possible, I may just change `OAuth1.exchangeForToken` to use POST request. The reason why I chose GET is because it seemed more semantic.

**Comment by sahat** [comment]
I remembered why OAuth1 had to use `GET`. Because of this: `popup.open(popupUrl)`. 

OAuth 2.0 providers don't have this issue because an authorization screen is accessed directly from the provider, e.g. `https://www.facebook.com/v2.3/dialog/oauth`.

With OAuth 1.0 and Twitter you cannot do that. If I find a workaround, I'll change Twitter example and all OAuth 1.0 `exchangeForToken` calls to use POST.

**Pull request closed without merging**
