### PR TITLE
added User.from_auth method for Ruby examples

### PR DESCRIPTION
**Pull request by elanperach**
as per Issue #571 by @aL3xa

You will need to have an Authorization model to accommodate it

  create_table "authorizations", force: :cascade do |t|
    t.string   "provider"
    t.string   "uid"
    t.string   "token"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "secret"
  end

### CODE REVIEW

**Comment by ACPK** [comment]
@elanperach Using your change, I hit an error "NoMethodError (undefined method `smash')" due to the line "params = params.smash.with_indifferent_access"

**Comment by elanperach** [comment]
@ACPK Added another commit with the smash method we added to the Hash Class.

Let me know if that did the trick.

**Comment by sahat** [comment]
@elanperach could you clean up the PR and remove unnecessary User fields?

**Comment by aligit** [comment]
dear @elanperach what is the purpose of #smash method?

**Comment by elanperach** [comment]
@aligit it is for flattening nested hashes.

**Comment by aligit** [comment]
thanks

**Pull request merged**
