### PR TITLE
renamed isLinking to redirect

### PR DESCRIPTION
**Pull request by sabrehagen**
renamed isLinking to redirect to match docs and intended purpose. this
improves readability of the code and links the documentation terminology
to variable names used in the code.

### CODE REVIEW

**Comment by sabrehagen** [comment]
found that redirect is the inverse of isLinking, so the simple rename to (config.loginRedirect && !redirect) does the opposite of the redirect intention. redirect=true will not redirect. changing code to logically correct version.

**Comment by amullins83** [comment]
I haven't got into the habit yet of reading existing pull requests before submitting new ones. I noticed that the "redirect" parameter wasn't really accessible from the `$auth.login` method, so I submitted PR #323, which also renames `isLinking` in the `setToken` method to `redirect`. Would you still approve of this change or do you think there are other edits needed?

**Comment by sabrehagen** [comment]
@amullins83 It hasn't been looked at by @sahat in 17 days, let's hope it happens soon...

**Comment by sahat** [comment]
Thanks @sabrehagen. There were only 2 places that needed to be updated after @amullins83's pull request.

**Pull request closed without merging**
