### PR TITLE
Store in memory if localStorage is not available

### PR DESCRIPTION
**Pull request by NicolasBlois**
This is usefull if Safari is in private mode

### CODE REVIEW

**Comment by sahat** [comment]
Thanks. One more thing - could you run `gulp` to generate these changes in `satellizer.min.js` as well?

**Comment by NicolasBlois** [comment]
Thank you Sahat for this module, it save me time. I use it for this project https://www.miletag.com. Actually in alpha release by invitation.

**Comment by sahat** [comment]
Thanks :+1:! Miletag looks good.

**Comment by NicolasBlois** [comment]
Frontend is made around angular material. That's why it looks good :santa: 
Thanks anyway

**Pull request merged**
