### PR TITLE
Golang Server example

### PR DESCRIPTION
**Pull request by celrenheit**
Hi,
I made a basic example of the server in Go.

What currently works:
- [x] Login with e-mail
- [x] Sign Up with e-mail
- [x] Get profile
- [x] Update profile
- [x] Facebook Login
- [x] Google Login
- [x] Twitter

### CODE REVIEW

**Comment by sahat** [comment]
Thanks which Go framework are you using? I'll merge it after Google, Facebook, Twitter are implemented, from there I think it should be straight forward for me to create other OAuth providers by following your code.

**Comment by celrenheit** [comment]
I not using a framework. It uses native http.Request and http.ResponseWriter with [gorilla/mux](https://github.com/gorilla/mux) for Routing and [codegangsta/negroni](https://github.com/codegangsta/negroni) for handling Middlewares. 
Do you prefer using goji framework ?
I'll try to add Google, Facebook, Twitter in the coming week.

**Comment by sahat** [comment]
@celrenheit I haven't had a chance to use Go-lang yet, so there is no prference for goji, martini, beegle or no framework. Whichever results in the simplest code to understand is good by me.

**Comment by celrenheit** [comment]
@sahat I am having some issues with Twitter oauth with the latest changes. The popup redirects to the homepage but does not close itself. I get the same behavior with the Node.js example.
I think it is coming from here: [https://github.com/sahat/satellizer/blob/master/satellizer.js#L691-L692](https://github.com/sahat/satellizer/blob/master/satellizer.js#L691-L692)

**Comment by sahat** [comment]
@celrenheit Are your back-end and front-end on different ports by any chance?

**Comment by sahat** [comment]
I just updated satellizer.js, let me know if it fixes the issue.

**Comment by celrenheit** [comment]
@sahat Yes thank you it fixed the issue and I didn't notice that now oauth_token and oauth-verifier were sent in the body of the request.

Yes I'm back-end and front-end primarily on Node.js and Golang for the backend. Angular and now playing with React for the front-end side.

I am having some issues with Google auth now, it keeps saying me: 
```json
{
  "error" : "invalid_grant"
}
```
There is something I did wrong because it works on the node.js example.

**Comment by sahat** [comment]
This could be the reason. Google expects you to send `grant_type: 'authorization_code'` in addition to client id, client secret and redirect url.

Glad that fixed the issue with Twitter, I was out of ideas if that still didn't work.

**Comment by celrenheit** [comment]
I sent exactly those information but I kept on falling into "invalid_grant". I also tried [third party library](https://github.com/bradrydzewski/go.auth) that handle OAuth but still the same error.
I'll try to find the reason.

**Comment by nodeEnthu** [comment]
Hi , I am gettting  same error while running this snippet 
 var accessTokenUrl = 'https://accounts.google.com/o/oauth2/token';
        var peopleApiUrl = 'https://www.googleapis.com/plus/v1/people/me/openIdConnect';
        var params = {
            code: req.body.code,
            client_id: req.body.clientId,
            client_secret: '6OZgHvGGk6YhCImOGoCvuxsR',
            redirect_uri: req.body.redirectUri,
            grant_type: 'authorization_code'
        };

        // Step 1. Exchange authorization code for access token.
        request.post(accessTokenUrl, {
            json: true,
            form: params
        }, function(err, response, token) {
            console.log('Access token ' + JSON.stringify(token));
            console.log('Response ' + JSON.stringify(response));
            var accessToken = token.access_token;
            var headers = {
                Authorization: 'Bearer ' + accessToken
            };

**Comment by celrenheit** [comment]
@nodeEnthu Yes I am having similar issue but didnt found yet where it comes from.

**Comment by nodeEnthu** [comment]
yeah .. I have spent too much time on it . going to log an issue

**Comment by sahat** [comment]
I will take a look at it tonight.

**Comment by sahat** [comment]
I have tried just about everything and now out of ideas as to what could be causing this error all of a sudden.

**Comment by sahat** [comment]
Keep getting the same issue even in the Google OAuth Playground...

screenshot 2015-05-19 17 56 11

**Comment by sahat** [comment]
I tracked down the issue to Google using forward slash in their authorization `code` which gets dropped when it is being parsed.

So before `code` is event sent back to the server it is already invalid. So the issue is with the Satellizer and I will try to resolve it asap.

**Comment by sahat** [comment]
@celrenheit it should be good to go, just pull the latest changes from master.

**Comment by celrenheit** [comment]
@sahat Thanks. That solved the issue.
I'm gonna simplify a bit the request process in a while.

**Comment by sahat** [comment]
Sounds good, please do simplify it as much as possible. I have never used Go before, so all the remaining providers that I am going to implement will be based on your code.

**Comment by sahat** [comment]
@celrenheit Is this good to merge now?

**Comment by celrenheit** [comment]
Yes I think it should be good

**Comment by sahat** [comment]
Great, thanks for all your contributions to this project! :+1:

**Pull request merged**
