### PR TITLE
Ruby on Rails example

### PR DESCRIPTION
**Pull request by simonasdev**
Ruby on Rails API made to work with satellizer (static files are served by sinatra). `lib/oauth/` is where the magic happens. Only facebook and google oauth implemented so far.

### CODE REVIEW

**Comment by sahat** [comment]
@simonasdev is it really necessary to use sinatra to serve static files?

**Comment by simonasdev** [comment]
It is, if we don't want to duplicate client side files in public folder. I was unable to specify from which path rails should serve static assets, it's not something that many people have done, so I haven't found a clear solution for this problem. Using sinatra is indeed a workaround, but, at least until someone tells me otherwise, we might just have to pick our poison in this case.

**Comment by sahat** [comment]
I see. I ran into the same problem with Rails and couldnt' figure out how to change the path of "public" directory.

So where exactly is Facebook and Google authentication handled? JWT encoding and decoding? Or something like "isAuthenticated" middleware?

**Comment by simonasdev** [comment]
Well facebook and google authentication endpoints are in auth_controller.rb and it is handled by OAuth module, `lib/oauth` (there isn't much more than couple of HTTP requests), and database authentication by User class, `app/models/user.rb`. In this case, user authentication is handled not by middleware, but by a `before_action :set_current_user, :authenticate_user!` callbacks, which are executed before all calls to /api. And JWT decoding and encoding is handled by Token class, `lib/token.rb`. I could explain in more detail if this is not comprehensible enough.

**Comment by sahat** [comment]
@simonasdev after giving it some considerations I would have liked if this example would be more explicit, instead of relying on auth libraries, just like I have in every single example so far.

**Comment by simonasdev** [comment]
I understand, but this is a library that I wrote specifically to work with satellizer. I abstracted controller methods to a class so new oauth providers could be easily implemented. I just wanted to be DRY, that's all :D And I think that this object oriented pattern should be clear enough even for newcomers. But if you want it to be more explicit, for the sake of this example, I can quickly make changes so all oauth code that would be executed is visible in corresponding controller action.

**Comment by sahat** [comment]
When I mentioned "explicit" I meant not using any OAuth library magic, but I'll still merge it for now. If I run into any issues with implementing other providers I'll update the code so it doesn't rely on OAuth libraries and instead do your own code for access token exchange, and grabbing profile information.

It's basically the same reason why I haven't used Passport in the Node.js example.

**Comment by jgorset** [comment]
This example doesn't actually contain the code for the `OAuth` module or the `Token` class, which is pretty confusing. Did you ignore the `lib` directory, @simonasdev?

**Comment by simonasdev** [comment]
Aaah, my bad, I didn't notice it, but the root satellizer .gitignore  had `lib` in it, that's why it didn't appear in the repository. So I moved the code to `app/models`. @sahat, will you be able to 're-merge' my last commit, or do I need to create a separate pull request?

**Comment by sahat** [comment]
@simonasdev once merged you will need to create a separate PR.

So, now you see my question from earlier makes more sense:
> So where exactly is Facebook and Google authentication handled? JWT encoding and decoding? Or something like "isAuthenticated" middleware?

**Comment by simonasdev** [comment]
Yeah, you're right, didn't think about the possibility that lib folder might get ignored. So now this whole example will actually make sense :D I created that new PR.

**Comment by jgorset** [comment]
Thanks @simonasdev! This helps me out a bunch.

**Pull request merged**
